config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  mount Sidekiq::Web => "/sidekiq"

  devise_for :users

  resources :images, only: [:create, :destroy]

  resources :campaigns do
    resources :contestants, only: [:index, :destroy]
  end

  get  "/campaign/:campaign_id/:secret_code", to: "contestants#show",  as: :contestant_registered
  get  "/campaign/:campaign_id",              to: "contestants#new"
  post "/campaign/:campaign_id",              to: "contestants#create", as: :contestant_register

  post "/resend_confirmation/:secret_code",   to: "resend_confirmations#create", as: :contestant_resend_confirmation
  get  "/confirmation/:confirmation_token",   to: "confirmations#edit", as: :contestant_confirmation

  get  "/:secret_code",                       to: "redirections#new",   as: :redirection

  root "home#index"
end

app/models/contestant.rb
class Contestant < ApplicationRecord
  paginates_per 100

  has_many :referred_contestants, class_name: "Contestant", foreign_key: :referred_by_id

  has_many :share_action_managements, dependent: :destroy
  has_many :share_action, -> { distinct }, through: :share_action_managements

  has_many :bonus_entry_managements, dependent: :destroy
  has_many :bonus_entry, -> { distinct }, through: :bonus_entry_managements

  belongs_to :campaign
  belongs_to :referred_by, class_name: "Contestant", optional: true

  validates :email, presence: true,
                    uniqueness: { scope: :campaign_id },
                    format: { with: URI::MailTo::EMAIL_REGEXP }, on: :create

  validates :secret_code, :confirmation_token, :referral_code, uniqueness: true

  before_create  :set_confirmation_token, :set_secret_code, :set_referral_code
  after_create   :send_confirmation_email
  before_destroy :destroy_bonus_entry_managements, :destroy_share_action_managements

  def confirm( confirmed_ip )
    update(confirmed: true, confirmed_at: Time.now.utc, confirmed_ip: confirmed_ip)
  end

  def resend_confirmation_email?
    return false if self.confirmed?
    return false if Time.now.before?(self.confirmation_sent_at + 24.hours)

    send_confirmation_email
  end

  private

  def send_confirmation_email
    ContestantMailer.with(contestant: self).confirmation_email.deliver_later
  end

  def set_secret_code
    loop do
      self.secret_code = SecureRandom.hex(3).upcase
      break unless self.class.exists?(secret_code: secret_code)
    end
  end

  def set_referral_code
    loop do
      self.referral_code = SecureRandom.hex(6)
      break unless self.class.exists?(referral_code: referral_code)
    end
  end

  def set_confirmation_token
    loop do
      self.confirmation_token = SecureRandom.hex(10)
      break unless self.class.exists?(confirmation_token: confirmation_token)
    end
  end

  def destroy_bonus_entry_managements
    self.bonus_entry_managements.destroy_all
  end

  def destroy_share_action_managements
    self.share_action_managements.destroy_all
  end
end

app/controllers/contestants_controller.rb
class ContestantsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[ show new create ]
  before_action :set_campaign, only: %i[ index show new create destroy ]
  before_action :set_contestant, only: %i[ show ]
  before_action :set_contestant_from_cookies, only: %i[ new ]

  def index
    @contestants = @campaign.contestants.page(params[:page])
  end

  def show
    redirect_to contestant_register_path(@campaign.slug) unless @contestant
  end

  def new
    if @contestant
      redirect_to contestant_registered_path( @contestant.campaign.slug, @contestant.secret_code )
    else
      @contestant = @campaign.contestants.new
    end
  end

  def create

    @contestant = @campaign.contestants.find_by(email: contestant_params[:email])

    respond_to do |format|
      if @contestant
        format.json {
          render json: {
            contestant: @contestant,
            redirect_to: contestant_registered_path(@campaign.slug, @contestant.secret_code)
          },
          status: :ok
        }
      else
        @contestant = @campaign.contestants.new(contestant_params)

        if @contestant.save
          format.json {
            render json: {
              contestant: @contestant,
              redirect_to: contestant_registered_path(@campaign.slug, @contestant.secret_code)
            },
            status: :created 
          }
        else
          format.json {
            render json: {
              message: @contestant.errors.full_messages.to_sentence
            },
            status: :unprocessable_entity
          }
        end
      end
    end
  end

  def destroy
    @contestant = @campaign.contestants.find_by(id: params[:id])

    respond_to do |format|
      if @contestant && @contestant.destroy
        format.html { redirect_back(fallback_location: root_path) }
      end
    end
  end

  private

  def set_campaign
    @campaign = Campaign.friendly.find(params[:campaign_id])
  rescue
    redirect_to root_url
  end

  def set_contestant
    @contestant = @campaign.contestants.find_by(secret_code: params[:secret_code])
  end

  def set_contestant_from_cookies
    @contestant = Contestant.find_by(secret_code: cookies[:contestant_secret_code])
  end

  def contestant_params
    params.require(:contestant).permit(:full_name, :email)
  end
end

app/views/contestants/_form.html.erb
<%= form_with(model: campaign) do |form| %>
  <% if campaign.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(campaign.errors.count, "error") %> prohibited this campaign from being saved:</h2>
    <ul>
      <% campaign.errors.each do |error| %>
      <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <p class="divider-text">
    <span class="bg-light"> 1. Giveaway Information </span>
  </p>
  <div class="mb-3">
    <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= form.label :description, class: "form-label" %>
    <%= form.text_area :description, id: "editor", class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= form.label :starts_at, class: "form-label" %>
    <%= form.datetime_field :starts_at, class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= form.label :ends_at, class: "form-label" %>
    <%= form.datetime_field :ends_at, class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= form.label :awarded_at, class: "form-label" %>
    <%= form.datetime_field :awarded_at, class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= form.label :time_zone, class: "form-label" %>
    <%= form.select :time_zone, ["Zone 1", "Zone 2", "Zone 3"], {}, { class: "form-control" } %>
  </div>
  <div class="mb-3">
    <%= form.label :offered_by_name, class: "form-label" %>
    <%= form.text_field :offered_by_name, class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= form.label :offered_by_url, class: "form-label" %>
    <%= form.text_field :offered_by_url, class: "form-control" %>
  </div>
  <p class="divider-text">
    <span class="bg-light"> 2. Setup Winner Prize </span>
  </p>
  <div class="mb-3">
    <%= form.label :number_of_winners, class: "form-label" %>
    <%= form.number_field :number_of_winners, class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= form.label :winner_prize_name, class: "form-label" %>
    <%= form.text_field :winner_prize_name, class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= form.label :winner_prize_value, class: "form-label" %>
    <%= form.number_field :winner_prize_value, class: "form-control" %>
  </div>
  <p class="divider-text">
    <span class="bg-light"> 3. Setup Runner-up Prize(Optional) </span>
  </p>
  <div class="mb-3">
    <%= form.label :number_of_runners_up, class: "form-label" %>
    <%= form.number_field :number_of_runners_up, class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= form.label :runner_up_prize_name, class: "form-label" %>
    <%= form.text_field :runner_up_prize_name, class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= form.label :runner_up_prize_value, class: "form-label" %>
    <%= form.number_field :runner_up_prize_value, class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= form.label :prize_images, class: "form-label" %>
    <%= form.file_field :prize_images, class: "form-control", multiple: true, direct_upload: false %>
  </div>
  <p class="divider-text">
    <span class="bg-light"> 4. Sharing </span>
  </p>
  <p class="divider-text">
    <span class="bg-light"> 5. Bonus Entries </span>
  </p>
  <div class="mb-3">
    <p>These are actions a contestant can take to get even more entries:</p>
  </div>
  <%= form.fields_for :bonus_entries do |bonus| %>
  <div class="mb-3">
    <%= bonus.label :type, class: "form-label" %>
    <%= bonus.text_field :type, class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= bonus.label :action_text, class: "form-label" %>
    <%= bonus.text_field :action_text, class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= bonus.label :action_url, class: "form-label" %>
    <%= bonus.text_field :action_url, class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= bonus.label :points, class: "form-label" %>
    <%= bonus.number_field :points, value: 2, class: "form-control" %>
  </div>
  <% end %>
  <p class="divider-text">
    <span class="bg-light"> 6. EU GDPR consent checkbox </span>
  </p>
  <div class="mb-3">
    <p>Are you planning to send your entrants marketing messages after the giveaway? Are any of your contestants located in the EU? If yes, or you’re not sure, enable the checkbox option below so your contestants can give clear consent as required by EU GDPR.:</p>
    <input class="form-check-input" type="checkbox" name="campaign[gdpr]" id="gdpr">
    <label class="form-check-label" for="gdpr">Require GDPR Consent</label>
  </div>
  <div class="actions" style="margin: 50px 0;">
    <%= form.submit "Create A Campaign", class: "btn btn-success" %>
  </div>
<% end %>

<script>
  ClassicEditor.create( document.querySelector( "#editor" ), {
    toolbar: [ "heading", "|", "bold", "italic", "link", "bulletedList", "numberedList", "blockQuote" ],
    heading: {
      options: [
        { model: "paragraph", title: "Paragraph", class: "ck-heading_paragraph" },
        { model: "heading1", view: "h1", title: "Heading 1", class: "ck-heading_heading1" },
        { model: "heading2", view: "h2", title: "Heading 2", class: "ck-heading_heading2" }
      ]
    }
  })
  .catch( error => {
    console.error( error );
  });
</script>

<style type="text/css">
  .ck-editor__editable_inline {
      min-height: 400px;
  }
  .field_with_errors{
    width: 100%;
  }
  .ck-editor__editable_inline {
    min-height: 200px;
  }
  .divider-text {
    position: relative;
    text-align: center;
    margin-top: 25px;
    margin-bottom: 25px;
  }
  .divider-text span {
    padding: 7px;
    font-size: 12px;
    position: relative;   
    z-index: 2;
  }
  .divider-text:after {
    content: "";
    position: absolute;
    width: 100%;
    border-bottom: 1px solid #ddd;
    top: 55%;
    left: 0;
    z-index: 1;
  }
  .btn-facebook {
    background-color: #405D9D;
    color: #fff;
  }
  .btn-twitter {
    background-color: #42AEEC;
    color: #fff;
  }
</style>

app/views/contestants/index.html.erb
<% content_for :title do %>
  List of contestants
<% end %>

<div class="container">
  <table class="table" style="margin-top: 25px;">
    <thead>
      <tr>
        <th scope="col" class="text-left">Email</th>
        <th scope="col" class="text-center">Points</th>
        <th scope="col" class="text-center">Referrals</th>
        <th scope="col" class="text-center">Registered IP</th>
        <th scope="col" class="text-center">Date Entered</th>
        <th scope="col" class="text-center">Resend</th>
        <th scope="col" class="text-center">Confirmed</th>
        <th scope="col" class="text-center"></th>
      </tr>
    </thead>
    <tbody>
      <% @contestants.each do |contestant| %>
        <tr>
          <td class="text-left">
            <%= contestant.email %>
          </td>
          <td class="text-center"><%= contestant.total_points %></td>
          <td class="text-center"><%= contestant.total_referrals %></td>
          <td class="text-center"><%= contestant.registered_ip %></td>
          <td class="text-center"><%= contestant.created_at.strftime("%b %d, %Y %H:%m") %></td>
          <td class="text-center">
            <% unless contestant.confirmed? %>
              <% if Time.now.before?(contestant.confirmation_sent_at + 24.hours) %>
                <h4 class="badge alert-danger">wait for 24h</h4>
              <% else %>
                <%= link_to "Resend Confirmation?",
                  contestant_resend_confirmation_path(contestant.secret_code),
                  data: {
                    remote: true,
                    turbo_method: :post
                  },
                  disabled: contestant.confirmed? ? true : false,
                  class: "small text-danger"
                %>
              <% end %>
            <% end %>
          </td>
          <td class="text-center">
            <% if contestant.confirmed? %>
              <span style="color: #198754;"><i class="fas fa-check-circle"></i></span>
            <% else %>
              <span style="color: red;"><i class="far fa-times-circle"></i></span>
            <% end %>
          </td>
          <td class="text-center">
            <%= link_to campaign_contestant_path(contestant.campaign, contestant.id), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: "delete-contestant" do %>
              <span style="color: red;"><i class="fas fa-trash-alt"></i></span>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <nav aria-label="Page navigation">
    <ul class="pagination">
      <%= paginate @contestants %>
    </ul>
  </nav>
  <br />
  <div class="row" style="margin-top: 35px;">
    <div class="row justify-content-center">        
      <div class="col-12 col-lg-8 my-4">
        <div class="text-center">
          <p class="mb-3"><%= link_to "Back to Dashboard", campaigns_path %></p>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  // $( document ).ready(function() {
  //   $(".delete-contestant").bind("ajax:success", function() {  
  //     $(this).closest('tr').fadeOut();
  //   });
  // });
</script>

app/views/contestants/new.html.erb
<% content_for :title do %>
  <%= @campaign.offered_by_name %> | <%= @campaign.title %>
<% end %>

<% content_for :facebook_properties do %>
  <meta property="og:url"         content="<%= root_url.chomp("/") + contestant_register_path(@campaign) %>" />
  <meta property="og:type"        content="website" />
  <meta property="og:title"       content="<%= @campaign.title %>" />
  <meta property="og:description" content="<%= @campaign.description %>" />
<% end %>

<div class="page-width page-width--narrow card mx-auto" style="max-width: 72.5rem; margin: 25px 0; box-shadow: 0 10px 25px 0 rgb(99 123 173 / 20%); border-radius: 20px;">
  <% if @campaign.images.any? %>
    <div data-controller="carousel" data-bs-ride="carousel" id="giveawayCarousel" class="carousel slide" style="height: 350px">
      <div class="carousel-inner">
        <% @campaign.images.each_with_index do |image, index| %>
          <div class="carousel-item <%= index.eql?(0) ? "active" : nil %>">
            <div class="d-block w-100" style="z-index: 99; height: 335px; border-radius: 20px 20px 0 0; background-image: url(<%= url_for(image.data) %>); background-repeat: no-repeat; background-position: center; background-size: cover;">
            </div>
          </div>
        <% end %>
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#giveawayCarousel" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#giveawayCarousel" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
      </button>
    </div>
  <% end %>
  <div class="card-body" style="box-shadow: 0 10px 35px 0 rgb(99 123 173 / 20%); margin: <%= @campaign.images.any? ? "-45px 0 0 0" : "0" %>; padding: 35px 44px; border-radius: 20px; background-color: #FFF; z-index: 9999;">
    <h1 class="card-title mb-4 text-center">
      <%= @campaign.title %>
    </h1>
    <% if @campaign.running? %>
      <div class="hr-title h6">
        <div>TIME LEFT</div>
      </div>
      <div data-controller="countdown" class="en d-flex text-center align-items-center basic-info">
        <div class="col-6 col-sm-2 col-md-3 h6 order-2 order-sm-1 basic-b">VALUE: $<%= "%.2f" % @campaign.winner_prize_value.round(2) %></div>
        <div class="col-12 col-sm-7 col-md-6 order-1 order-sm-2 hr-b-small">
          <div data-ends-at="<%= @campaign.ends_at.in_time_zone %>" id="countdown" class="countdown time-left d-flex justify-content-center">
            <div class="time-unity">
              <span class="days" style="font-weight: bold;">*</span><br><span class="label">DAYS</span>
            </div>
            <div>:</div>
            <div class="time-unity">
              <span class="hours" style="font-weight: bold;">*</span><br><span class="label">HOURS</span>
            </div>
            <div>:</div>
            <div class="time-unity">
              <span class="minutes" style="font-weight: bold;">*</span><br><span class="label">MIN</span>
            </div>
            <div>:</div>
            <div class="time-unity">
              <span class="seconds" style="font-weight: bold;">*</span><br><span class="label">SEC</span>
            </div>
          </div>
        </div>
        <div class="col-6 col-sm-2 col-md-3 h6 order-3 basic-b">WINNER(s): <%= @campaign.number_of_winners %></div>
      </div>
      <div class="hr-arrow-down"></div>
      <div class="mb-3" style="margin-top: 1rem;">
        <p class="text-center"><b>Enter with your email address:</b></p>
      </div>
      <div class="register-form mx-auto" style="max-width: 440px; margin: 1rem 0;">
        <%= form_with(
          url: contestant_register_path(@campaign),
          model: @contestant,
          data: {
            "type": "html",
            "controller": "contestant",
            "target": "contestant.form",
            "contestant-url": contestant_register_path(@campaign)
          },
          class: "needs-validation"
        ) do |form| %>

          <div class="">
            <div class="input-group has-validation">
              <%= form.text_field :email, data: { "contestant-target": "email" }, class: "form-control", placeholder: "Enter your email", required: true %>
              <%=
                form.submit "ENTER",
                data: {
                  remote: true,
                  action: "click->contestant#ajaxSubmit"
                },
                disabled: true,
                class: "btn btn-success"
              %>
              <div class="invalid-feedback">Your have entered an invalid e-mail address!</div>
            </div>
          </div>
          <p class="text-muted mt-2" style="text-align: center;">
            <label class="form-check-label">
              <input class="form-check-input mr-2" data-contestant-target="gdpr" type="checkbox" required=""> <small><i>I consent to getting sale, promotion, or marketing email(*)</i></small>
            </label> 
          </p>
        <% end %>
      </div>
    <% end %>

    <div class="hr-top mt-5"></div>

    <% if @campaign.upcoming? %>
      <div class="pt-4 pb-5">
        <h2 class="text-center">
          <i>This giveaway hasn't started yet!</i>
        </h2>
      </div>
    <% end %>
    
    <% if @campaign.running? %>
      <div class="pt-4 pb-5"><%= @campaign.description.html_safe %></div>
    <% end %>

    <% if @campaign.expired? %>
      <div class="pt-5">
        <h2 class="text-center">
          <i>Oops, Giveaway Has Ended!</i>
        </h2>
      </div>

      <div class="hr-top mt-5"></div>

      <div class="pt-3">
        <div class="mx-3 text-center">
          <small>PRIZES AWARDED: <span style="opacity: .5;">OCTOBER 17, 2021 12:00 AM</span></small>
        </div>
        <div class="mx-3 text-center">
          <small>GIVEAWAY ENDED: <span style="opacity: .5;">OCTOBER 16, 2021 12:00 AM</span></small>
        </div>
      </div>
    <% end %>

    <p class="divider-text">
      <span class="bg-light">OFFERED BY:</span>
    </p>
    <div class="row mb-3" style="padding-top: 15px;">
      <div class="d-flex flex-wrap justify-content-center">
        <div class="mx-3"><small><span class="h6">TIME ZONE: <%= @campaign.time_zone.upcase %></span></small></div>
        <div class="mx-3"><small><span class="h6">OFFERED BY: <%= @campaign.offered_by_name.upcase %></span></small></div>
      </div>
    </div>
    <p class="divider-text-footer">
      <span class="bg-light">Enter sweepstakes and receive exclusive offers from <%= @campaign.offered_by_name %>. Unsubscribe anytime.<br /><a href="#">Read official rules.</a></span>
    </p>
  </div>
</div>

<style type="text/css">
  @media (min-width: 960px) {
    .card {
      max-width: 50% !important;
    }
  }

  @media (max-width: 720px) {
    .card-body {
      padding-right: 25px !important;
      padding-left: 25px !important;
    }
  }

  @media (max-width: 575px) {
    .hr-arrow-down {
      height: 7px;
    }
  }

  .d-flex {
    display: -webkit-box !important;
    display: -ms-flexbox !important;
    display: flex !important;
  }

  .hr-top {
    margin-top: 31px;
    position: relative;
  }

  .hr-plain,
  .hr-top {
    background-image: url(//kingsumo.b-cdn.net/img/giv/hr.svg);
    background-repeat: repeat-x;
    background-size: auto 2px;
    background-position-y: 0;
    width: 100%;
    height: 2px;
    display: block;
  }

  .mt-5,
  .my-5 {
    margin-top: 3rem !important;
  }

  .pb-5,
  .py-5 {
    padding-bottom: 2rem !important;
  }

  .pt-4,
  .py-4 {
    padding-top: 2rem !important;
  }

  .order-1 {
    order: 1 !important;
  }

  .order-2 {
    -webkit-box-ordinal-group: 3;
    -ms-flex-order: 2;
    order: 2;
  }

  .hr-arrow-down {
    background-image: url(//kingsumo.b-cdn.net/img/giv/hr.svg);
    background-repeat: repeat-x;
    background-size: auto 2px;
    background-position-y: 0;
    width: 100%;
    height: 23px;
    display: block;
    position: relative;
  }

  .basic-info {
    -webkit-box-pack: center;
    -ms-flex-pack: center;
    justify-content: center;
    -ms-flex-wrap: wrap;
    flex-wrap: wrap;
  }

  .align-items-center {
    -webkit-box-align: center !important;
    -ms-flex-align: center !important;
    align-items: center !important;
  }

  .basic-b:first-of-type {
    border-right: 2px solid #e9eff4;
  }

  @media (max-width: 575px) {
    .basic-b {
      padding: .4rem 0;
    }

    .hr-b-small {
      border-bottom: 2px solid #e9eff4;
      margin-bottom: .6rem;
    }

    .col-6 {
      -ms-flex: 0 0 50%;
      flex: 0 0 50%;
      max-width: 50%;
    }
  }

  p {
    font-size: 1rem;
  }

  .register-form {
    width: 100%;
  }

  .card {
    border: none;
  }

  .card .card-body {
    width: 100%;
  }

  .field_with_errors {
    width: 100%;
  }

  .ck-editor__editable_inline {
    min-height: 200px;
  }

  .divider-text {
    position: relative;
    text-align: center;
    margin-top: 25px;
    margin-bottom: 25px;
  }

  .divider-text span {
    padding: 7px;
    font-size: 12px;
    position: relative;
    z-index: 2;
  }

  .divider-text:after {
    content: "";
    position: absolute;
    width: 100%;
    border-bottom: 1px solid #ddd;
    top: 55%;
    left: 0;
    z-index: 1;
  }

  .divider-text-footer {
    position: relative;
    text-align: center;
    margin-top: 50px;
    margin-bottom: 25px;
  }

  .divider-text-footer span {
    width: 100%;
    display: block;
    padding: 7px;
    font-size: 12px;
    position: relative;
    border-top: 1px solid #ddd;
    border-bottom: 1px solid #ddd;
    z-index: 2;
  }

  .btn-facebook {
    background-color: #405D9D;
    color: #fff;
  }

  .btn-twitter {
    background-color: #42AEEC;
    color: #fff;
  }

  .time-left {
    line-height: 2.2rem;
    font-size: 2.2rem;
    font-weight: 300;
    text-align: center;
    padding: 18px 0 13px;
  }

  .time-unity {
    font-family: Roboto Mono, Roboto, sans-serif;
    margin: auto 7px;
  }

  .time-unity span.label {
    font-family: Roboto, sans-serif;
    font-size: .8rem;
    font-weight: 500;
    opacity: .5;
  }

  .hr-title,
  .hr-title div {
    text-align: center;
    background-color: #fff;
  }

  .hr-title {
    background-image: url(//kingsumo.b-cdn.net/img/giv/hr.svg);
    background-repeat: repeat-x;
    background-size: auto 2px;
    background-position-y: 7px;
    width: auto;
    margin: 0 auto;
  }

  .h6,
  h6 {
    letter-spacing: .04rem;
    font-weight: 500;
  }

  .hr-title,
  .hr-title div {
    text-align: center;
    background-color: #fff;
  }

  .hr-title div {
    display: inline-block;
    padding: 0 10px;
  }
</style>

<script src="<%= root_url %>javascript/iframeResizer.contentWindow.min.js"></script>