config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  mount Sidekiq::Web => "/sidekiq"

  devise_for :users

  resources :images, only: [:create, :destroy]

  resources :campaigns do
    resources :contestants, only: [:index, :destroy]
  end

  get  "/campaign/:campaign_id/:secret_code", to: "contestants#show",  as: :contestant_registered
  get  "/campaign/:campaign_id",              to: "contestants#new"
  post "/campaign/:campaign_id",              to: "contestants#create", as: :contestant_register

  post "/resend_confirmation/:secret_code",   to: "resend_confirmations#create", as: :contestant_resend_confirmation
  get  "/confirmation/:confirmation_token",   to: "confirmations#edit", as: :contestant_confirmation

  get  "/:secret_code",                       to: "redirections#new",   as: :redirection

  root "home#index"
end

app/views/layouts/_flash_messages.html.erb
<% content_for :javascript do %>
  <%= content_tag(:div, nil, id: 'shopify-app-flash', data: { flash: { notice: flash[:notice], error: flash[:error] } }) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title><%= yield :title %></title>
    <%= favicon_link_tag "/favicon.png" %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "//use.fontawesome.com/releases/v5.15.4/css/all.css" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <% unless controller_name == "contestants" && ["show", "new"].include?(action_name) %>
    <nav class="navbar navbar-expand-lg navbar-dark bg-success">
      <div class="container container-fluid">
        <strong><%= link_to 'MyCake', root_url, class: "navbar-brand" %></strong>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <% if user_signed_in? %>
        <div class="collapse navbar-collapse justify-content-center" id="navbarNavAltMarkup">
          <div class="navbar-nav" style="margin-left: -92.61px;">
            <%= link_to 'Dashboard', campaigns_url, class: "nav-link active text-uppercase" %>
            <%= link_to 'Account', edit_user_registration_path, class: "nav-link active text-uppercase" %>
            <%= link_to 'Sign out', destroy_user_session_path, class: "nav-link active text-uppercase", data: { turbo_method: :delete } %>
          </div>
        </div>
        <% else %>
        <div class="collapse navbar-collapse justify-content-center" id="navbarNavAltMarkup">
          <div class="navbar-nav" style="margin-left: -92.61px;">
            <%= link_to 'Home', root_url, class: "nav-link active text-uppercase" %>
            <%= link_to 'Sign up', new_user_registration_path, class: "nav-link active text-uppercase" %>
            <%= link_to 'Sign in', new_user_session_path, class: "nav-link active text-uppercase" %>
          </div>
        </div>
        <% end %>
      </div>
    </nav>
    <% end %>
    <% if notice %>
    <div class="alert alert-success" role="alert">
      <%= notice %>
    </div>
    <% end %>
    <% if alert %>
    <div class="alert alert-danger" role="alert">
      <%= alert %>
    </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/layouts/embedded_app.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <% application_name = ShopifyApp.configuration.application_name %>
    <title><%= application_name %></title>
    <%= stylesheet_link_tag 'application' %>
    <% if ShopifyApp.use_webpacker? %>
      <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <% else %>
      <%= javascript_include_tag 'application', "data-turbolinks-track" => true %>
    <% end %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="app-wrapper">
      <div class="app-content">
        <main role="main">
          <%= yield %>
        </main>
      </div>
    </div>

    <%= render 'layouts/flash_messages' %>

    <script src="https://unpkg.com/@shopify/app-bridge@2"></script>

    <%= content_tag(:div, nil, id: 'shopify-app-init', data: {
      api_key: ShopifyApp.configuration.api_key,
      shop_origin: @shop_origin || (@current_shopify_session.domain if @current_shopify_session),
      host: @host,
      debug: Rails.env.development?
    } ) %>

    <% if content_for?(:javascript) %>
      <div id="ContentForJavascript" data-turbolinks-temporary>
        <%= yield :javascript %>
      </div>
    <% end %>
  </body>
</html>